# Generated by Django 4.2.7 on 2026-01-09 11:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Antibiotics, Pain Relief)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medicine name (e.g., Paracetamol 500mg)', max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique identifier for the medicine', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the medicine', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of the medicine batch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Medicine category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='medicines_m_sku_5bae82_idx'), models.Index(fields=['category'], name='medicines_m_categor_1d7437_idx'), models.Index(fields=['expiry_date'], name='medicines_m_expiry__a86637_idx')],
            },
        ),
    ]
