# Generated by Django 4.2.7 on 2026-02-13 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this medicine",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name (e.g., Antibiotics, Pain Relief)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit - unique identifier for the medicine",
                max_length=50,
            ),
        ),
    ]

