# Generated by Django 4.2.7 on 2026-02-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_backfill_default_pharmacy"),
        ("medicines", "0002_tenant_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this medicine",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("pharmacy", "name"), name="uniq_category_pharmacy_name"),
        ),
        migrations.AddConstraint(
            model_name="medicine",
            constraint=models.UniqueConstraint(fields=("pharmacy", "sku"), name="uniq_medicine_pharmacy_sku"),
        ),
    ]

