# Generated by Django 4.2.7 on 2026-04-27 06:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_enforce_tenant_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode used for scanner-based lookup', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Acquisition cost per unit for profit analytics', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['barcode'], name='medicines_m_barcode_ac4d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('pharmacy', 'barcode'), name='uniq_medicine_pharmacy_barcode'),
        ),
    ]
