# Generated by Django 4.2.7 on 2026-02-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy where the sale was recorded",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy where this item was sold",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_items",
                to="tenants.pharmacy",
            ),
        ),
    ]

