# Generated by Django 4.2.7 on 2026-02-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_backfill_default_pharmacy"),
        ("sales", "0002_tenant_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy where the sale was recorded",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy where this item was sold",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_items",
                to="tenants.pharmacy",
            ),
        ),
    ]

