# Generated by Django 4.2.7 on 2026-04-01 11:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_enforce_tenant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal (quantity x unit price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
