# Generated by Django 4.2.7 on 2026-02-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                help_text="Pharmacy this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.pharmacy",
            ),
        ),
    ]

