# Generated by Django 4.2.7 on 2026-02-24 00:00

from django.db import migrations, models


def migrate_legacy_manager_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="PHARMACY_MANAGER").update(role="MANAGER")


def reverse_migrate_legacy_manager_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="MANAGER").update(role="PHARMACY_MANAGER")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_pharmacy"),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_manager_role,
            reverse_migrate_legacy_manager_role,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("PHARMACIST", "Pharmacist"),
                ],
                default="MANAGER",
                help_text="User role determines access level",
                max_length=20,
            ),
        ),
    ]
