# Generated by Django 4.2.7 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('PHARMACIST', 'Pharmacist'), ('CASHIER', 'Cashier')], default='MANAGER', help_text='User role determines access level', max_length=20),
        ),
    ]
