# Generated by Django 4.2.7 on 2026-02-13 00:15

from django.db import migrations


def backfill_default_pharmacy(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Pharmacy = apps.get_model("tenants", "Pharmacy")
    Category = apps.get_model("medicines", "Category")
    Medicine = apps.get_model("medicines", "Medicine")
    Sale = apps.get_model("sales", "Sale")
    SaleItem = apps.get_model("sales", "SaleItem")
    Inventory = apps.get_model("inventory", "Inventory")
    ReorderRecommendation = apps.get_model("inventory", "ReorderRecommendation")

    owner = User.objects.filter(is_superuser=True).order_by("id").first()
    if owner is None:
        owner = User.objects.order_by("id").first()
    if owner is None:
        owner = User.objects.create_user(
            username="system_owner",
            email="system-owner@example.com",
            password=None,
            is_active=True,
        )
        owner.set_unusable_password()
        owner.save(update_fields=["password"])

    default_pharmacy, _ = Pharmacy.objects.get_or_create(
        name="Default Pharmacy",
        defaults={
            "owner_id": owner.id,
            "plan_type": "BASIC",
        },
    )

    if default_pharmacy.owner_id != owner.id:
        default_pharmacy.owner_id = owner.id
        default_pharmacy.save(update_fields=["owner"])

    User.objects.filter(pharmacy__isnull=True).update(pharmacy_id=default_pharmacy.id)
    Category.objects.filter(pharmacy__isnull=True).update(pharmacy_id=default_pharmacy.id)
    Medicine.objects.filter(pharmacy__isnull=True).update(pharmacy_id=default_pharmacy.id)
    Sale.objects.filter(pharmacy__isnull=True).update(pharmacy_id=default_pharmacy.id)

    medicine_pharmacy_map = dict(Medicine.objects.values_list("id", "pharmacy_id"))
    for inventory in Inventory.objects.filter(pharmacy__isnull=True).iterator():
        inventory.pharmacy_id = medicine_pharmacy_map.get(inventory.medicine_id, default_pharmacy.id)
        inventory.save(update_fields=["pharmacy"])

    for recommendation in ReorderRecommendation.objects.filter(pharmacy__isnull=True).iterator():
        recommendation.pharmacy_id = medicine_pharmacy_map.get(recommendation.medicine_id, default_pharmacy.id)
        recommendation.save(update_fields=["pharmacy"])

    sale_pharmacy_map = dict(Sale.objects.values_list("id", "pharmacy_id"))
    for item in SaleItem.objects.filter(pharmacy__isnull=True).iterator():
        item.pharmacy_id = sale_pharmacy_map.get(item.sale_id, default_pharmacy.id)
        item.save(update_fields=["pharmacy"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("accounts", "0002_user_pharmacy"),
        ("medicines", "0002_tenant_fields"),
        ("inventory", "0002_tenant_fields"),
        ("sales", "0002_tenant_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_default_pharmacy, reverse_code=noop_reverse),
    ]

