# Generated by Django 4.2.7 on 2026-02-24 00:00

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_subscription_fields(apps, schema_editor):
    Pharmacy = apps.get_model("tenants", "Pharmacy")
    now = timezone.now()

    plan_limits = {
        "BASIC": {"max_users": 3, "max_medicines": 200, "max_monthly_sales": 1000},
        "PRO": {"max_users": 10, "max_medicines": 2000, "max_monthly_sales": 10000},
        "ENTERPRISE": {"max_users": None, "max_medicines": None, "max_monthly_sales": None},
    }

    for pharmacy in Pharmacy.objects.all().iterator():
        if pharmacy.subscription_start is None:
            pharmacy.subscription_start = now
        if pharmacy.subscription_end is None:
            pharmacy.subscription_end = pharmacy.subscription_start + timedelta(days=30)

        limits = plan_limits.get(pharmacy.plan_type, plan_limits["BASIC"])
        if pharmacy.max_users is None and limits["max_users"] is not None:
            pharmacy.max_users = limits["max_users"]
        if pharmacy.max_medicines is None and limits["max_medicines"] is not None:
            pharmacy.max_medicines = limits["max_medicines"]
        if pharmacy.max_monthly_sales is None and limits["max_monthly_sales"] is not None:
            pharmacy.max_monthly_sales = limits["max_monthly_sales"]

        if pharmacy.plan_type == "ENTERPRISE":
            pharmacy.max_users = None
            pharmacy.max_medicines = None
            pharmacy.max_monthly_sales = None

        if pharmacy.is_active is None:
            pharmacy.is_active = True

        pharmacy.save(
            update_fields=[
                "subscription_start",
                "subscription_end",
                "is_active",
                "max_users",
                "max_medicines",
                "max_monthly_sales",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_backfill_default_pharmacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="max_users",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="max_medicines",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="max_monthly_sales",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_subscription_fields, reverse_code=noop_reverse),
    ]
