# Generated by Django 4.2.7 on 2026-01-09 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_quantity', models.PositiveIntegerField(help_text='Recommended quantity to order', validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField(help_text='Reason for the recommendation (e.g., Low stock, High demand)')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the recommendation', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', help_text='Status of the recommendation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reorders', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(help_text='Medicine that needs reordering', on_delete=django.db.models.deletion.CASCADE, related_name='reorder_recommendations', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Reorder Recommendation',
                'verbose_name_plural': 'Reorder Recommendations',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_r_status_f84d77_idx'), models.Index(fields=['priority'], name='inventory_r_priorit_b1cf98_idx'), models.Index(fields=['created_at'], name='inventory_r_created_9fd262_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock_level', models.PositiveIntegerField(default=10, help_text='Minimum stock level before reorder is recommended', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_stock_level', models.PositiveIntegerField(default=100, help_text='Maximum stock level (target restock amount)', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_restocked_date', models.DateTimeField(blank=True, help_text='Date when inventory was last restocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(help_text='Medicine this inventory record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['medicine__name'],
                'indexes': [models.Index(fields=['current_stock'], name='inventory_i_current_13b727_idx')],
            },
        ),
    ]
