# Generated by Django 4.2.7 on 2026-02-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this inventory record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="tenants.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="reorderrecommendation",
            name="pharmacy",
            field=models.ForeignKey(
                help_text="Pharmacy that owns this recommendation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reorder_recommendations",
                to="tenants.pharmacy",
            ),
        ),
    ]

